// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'f3d162a686c9b0d6f8b99aa177c8976443018f5b370e781ce4f4a59d215b4a95'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Membership: {
      readonly mid: CodecTypes['pg/int4@1']['output'];
      readonly mname: Varchar<50>;
      readonly score: CodecTypes['pg/int4@1']['output'];
    };
    readonly Order: {
      readonly createat: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly oid: CodecTypes['pg/int4@1']['output'];
      readonly uid: CodecTypes['pg/int4@1']['output'];
    };
    readonly OrderDetail: {
      readonly oid: CodecTypes['pg/int4@1']['output'];
      readonly pid: CodecTypes['pg/int4@1']['output'];
      readonly qty: CodecTypes['pg/int4@1']['output'];
      readonly unit_price: Numeric<10, 2>;
    };
    readonly Product: {
      readonly pid: CodecTypes['pg/int4@1']['output'];
      readonly pname: Varchar<100>;
      readonly price: Numeric<10, 2>;
      readonly quantity: CodecTypes['pg/int4@1']['output'];
    };
    readonly Role: {
      readonly roleid: CodecTypes['pg/int4@1']['output'];
      readonly rolename: Varchar<50>;
    };
    readonly Shipment: {
      readonly oid: CodecTypes['pg/int4@1']['output'];
      readonly shipid: CodecTypes['pg/int4@1']['output'];
      readonly status: Varchar<50>;
    };
    readonly User: {
      readonly fullname: Varchar<100>;
      readonly mid: CodecTypes['pg/int4@1']['output'];
      readonly password: Varchar<255>;
      readonly roleid: CodecTypes['pg/int4@1']['output'];
      readonly uid: CodecTypes['pg/int4@1']['output'];
      readonly username: Varchar<50>;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Membership: {
      readonly mid: CodecTypes['pg/int4@1']['input'];
      readonly mname: CodecTypes['sql/varchar@1']['input'];
      readonly score: CodecTypes['pg/int4@1']['input'];
    };
    readonly Order: {
      readonly createat: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly oid: CodecTypes['pg/int4@1']['input'];
      readonly uid: CodecTypes['pg/int4@1']['input'];
    };
    readonly OrderDetail: {
      readonly oid: CodecTypes['pg/int4@1']['input'];
      readonly pid: CodecTypes['pg/int4@1']['input'];
      readonly qty: CodecTypes['pg/int4@1']['input'];
      readonly unit_price: CodecTypes['pg/numeric@1']['input'];
    };
    readonly Product: {
      readonly pid: CodecTypes['pg/int4@1']['input'];
      readonly pname: CodecTypes['sql/varchar@1']['input'];
      readonly price: CodecTypes['pg/numeric@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
    };
    readonly Role: {
      readonly roleid: CodecTypes['pg/int4@1']['input'];
      readonly rolename: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Shipment: {
      readonly oid: CodecTypes['pg/int4@1']['input'];
      readonly shipid: CodecTypes['pg/int4@1']['input'];
      readonly status: CodecTypes['sql/varchar@1']['input'];
    };
    readonly User: {
      readonly fullname: CodecTypes['sql/varchar@1']['input'];
      readonly mid: CodecTypes['pg/int4@1']['input'];
      readonly password: CodecTypes['sql/varchar@1']['input'];
      readonly roleid: CodecTypes['pg/int4@1']['input'];
      readonly uid: CodecTypes['pg/int4@1']['input'];
      readonly username: CodecTypes['sql/varchar@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Membership: {
      readonly mid: CodecTypes['pg/int4@1']['output'];
      readonly mname: Varchar<50>;
      readonly score: CodecTypes['pg/int4@1']['output'];
    };
    readonly Order: {
      readonly createat: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly oid: CodecTypes['pg/int4@1']['output'];
      readonly uid: CodecTypes['pg/int4@1']['output'];
    };
    readonly OrderDetail: {
      readonly oid: CodecTypes['pg/int4@1']['output'];
      readonly pid: CodecTypes['pg/int4@1']['output'];
      readonly qty: CodecTypes['pg/int4@1']['output'];
      readonly unit_price: Numeric<10, 2>;
    };
    readonly Product: {
      readonly pid: CodecTypes['pg/int4@1']['output'];
      readonly pname: Varchar<100>;
      readonly price: Numeric<10, 2>;
      readonly quantity: CodecTypes['pg/int4@1']['output'];
    };
    readonly Role: {
      readonly roleid: CodecTypes['pg/int4@1']['output'];
      readonly rolename: Varchar<50>;
    };
    readonly Shipment: {
      readonly oid: CodecTypes['pg/int4@1']['output'];
      readonly shipid: CodecTypes['pg/int4@1']['output'];
      readonly status: Varchar<50>;
    };
    readonly User: {
      readonly fullname: Varchar<100>;
      readonly mid: CodecTypes['pg/int4@1']['output'];
      readonly password: Varchar<255>;
      readonly roleid: CodecTypes['pg/int4@1']['output'];
      readonly uid: CodecTypes['pg/int4@1']['output'];
      readonly username: Varchar<50>;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Membership: {
      readonly mid: CodecTypes['pg/int4@1']['input'];
      readonly mname: CodecTypes['sql/varchar@1']['input'];
      readonly score: CodecTypes['pg/int4@1']['input'];
    };
    readonly Order: {
      readonly createat: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly oid: CodecTypes['pg/int4@1']['input'];
      readonly uid: CodecTypes['pg/int4@1']['input'];
    };
    readonly OrderDetail: {
      readonly oid: CodecTypes['pg/int4@1']['input'];
      readonly pid: CodecTypes['pg/int4@1']['input'];
      readonly qty: CodecTypes['pg/int4@1']['input'];
      readonly unit_price: CodecTypes['pg/numeric@1']['input'];
    };
    readonly Product: {
      readonly pid: CodecTypes['pg/int4@1']['input'];
      readonly pname: CodecTypes['sql/varchar@1']['input'];
      readonly price: CodecTypes['pg/numeric@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
    };
    readonly Role: {
      readonly roleid: CodecTypes['pg/int4@1']['input'];
      readonly rolename: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Shipment: {
      readonly oid: CodecTypes['pg/int4@1']['input'];
      readonly shipid: CodecTypes['pg/int4@1']['input'];
      readonly status: CodecTypes['sql/varchar@1']['input'];
    };
    readonly User: {
      readonly fullname: CodecTypes['sql/varchar@1']['input'];
      readonly mid: CodecTypes['pg/int4@1']['input'];
      readonly password: CodecTypes['sql/varchar@1']['input'];
      readonly roleid: CodecTypes['pg/int4@1']['input'];
      readonly uid: CodecTypes['pg/int4@1']['input'];
      readonly username: CodecTypes['sql/varchar@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Membership = {
    mid: CodecTypes['pg/int4@1']['output'];
    mname: Varchar<50>;
    score: CodecTypes['pg/int4@1']['output'];
    users: public_User[];
    readonly [RelationKeys]?: 'users';
  };
  export type public_Order = {
    createat: CodecTypes['pg/timestamp-temporal@1']['output'];
    oid: CodecTypes['pg/int4@1']['output'];
    uid: CodecTypes['pg/int4@1']['output'];
    orderDetails: public_OrderDetail[];
    shipments: public_Shipment[];
    user: public_User;
    readonly [RelationKeys]?: 'orderDetails' | 'shipments' | 'user';
  };
  export type public_OrderDetail = {
    oid: CodecTypes['pg/int4@1']['output'];
    pid: CodecTypes['pg/int4@1']['output'];
    qty: CodecTypes['pg/int4@1']['output'];
    unit_price: Numeric<10, 2>;
    order: public_Order;
    product: public_Product;
    readonly [RelationKeys]?: 'order' | 'product';
  };
  export type public_Product = {
    pid: CodecTypes['pg/int4@1']['output'];
    pname: Varchar<100>;
    price: Numeric<10, 2>;
    quantity: CodecTypes['pg/int4@1']['output'];
    orderDetails: public_OrderDetail[];
    readonly [RelationKeys]?: 'orderDetails';
  };
  export type public_Role = {
    roleid: CodecTypes['pg/int4@1']['output'];
    rolename: Varchar<50>;
    users: public_User[];
    readonly [RelationKeys]?: 'users';
  };
  export type public_Shipment = {
    oid: CodecTypes['pg/int4@1']['output'];
    shipid: CodecTypes['pg/int4@1']['output'];
    status: Varchar<50>;
    order: public_Order;
    readonly [RelationKeys]?: 'order';
  };
  export type public_User = {
    fullname: Varchar<100>;
    mid: CodecTypes['pg/int4@1']['output'];
    password: Varchar<255>;
    roleid: CodecTypes['pg/int4@1']['output'];
    uid: CodecTypes['pg/int4@1']['output'];
    username: Varchar<50>;
    membership: public_Membership;
    orders: public_Order[];
    role: public_Role;
    readonly [RelationKeys]?: 'membership' | 'orders' | 'role';
  };
}

export declare const models: {
  public: {
    Membership: Models.public_Membership;
    Order: Models.public_Order;
    OrderDetail: Models.public_OrderDetail;
    Product: Models.public_Product;
    Role: Models.public_Role;
    Shipment: Models.public_Shipment;
    User: Models.public_User;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Membership: {
              columns: {
                readonly mid: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly mname: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly score: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['mid'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Order: {
              columns: {
                readonly createat: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                };
                readonly oid: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly uid: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['oid'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Order_uid_idx_47f7925b';
                  readonly prefix: 'Order_uid_idx';
                  readonly columns: readonly ['uid'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Order';
                    readonly columns: readonly ['uid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['uid'];
                  };
                },
              ];
            };
            readonly OrderDetail: {
              columns: {
                readonly oid: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly pid: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly qty: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly unit_price: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 10; readonly scale: 2 };
                };
              };
              primaryKey: { readonly columns: readonly ['oid', 'pid'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'OrderDetail_oid_idx_1611d4a7';
                  readonly prefix: 'OrderDetail_oid_idx';
                  readonly columns: readonly ['oid'];
                  readonly unique: false;
                },
                {
                  readonly name: 'OrderDetail_pid_idx_1f49d342';
                  readonly prefix: 'OrderDetail_pid_idx';
                  readonly columns: readonly ['pid'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'OrderDetail';
                    readonly columns: readonly ['oid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Order';
                    readonly columns: readonly ['oid'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'OrderDetail';
                    readonly columns: readonly ['pid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Product';
                    readonly columns: readonly ['pid'];
                  };
                },
              ];
            };
            readonly Product: {
              columns: {
                readonly pid: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly pname: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly price: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 10; readonly scale: 2 };
                };
                readonly quantity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['pid'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Role: {
              columns: {
                readonly roleid: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly rolename: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
              };
              primaryKey: { readonly columns: readonly ['roleid'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Shipment: {
              columns: {
                readonly oid: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly shipid: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly status: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
              };
              primaryKey: { readonly columns: readonly ['shipid'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Shipment_oid_idx_1611d4a7';
                  readonly prefix: 'Shipment_oid_idx';
                  readonly columns: readonly ['oid'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Shipment';
                    readonly columns: readonly ['oid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Order';
                    readonly columns: readonly ['oid'];
                  };
                },
              ];
            };
            readonly User: {
              columns: {
                readonly fullname: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly mid: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly roleid: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly uid: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly username: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
              };
              primaryKey: { readonly columns: readonly ['uid'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'User_mid_idx_f4dbf00d';
                  readonly prefix: 'User_mid_idx';
                  readonly columns: readonly ['mid'];
                  readonly unique: false;
                },
                {
                  readonly name: 'User_roleid_idx_e2ab003b';
                  readonly prefix: 'User_roleid_idx';
                  readonly columns: readonly ['roleid'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['roleid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Role';
                    readonly columns: readonly ['roleid'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['mid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Membership';
                    readonly columns: readonly ['mid'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Membership: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Membership';
    };
    readonly Order: { readonly namespace: 'public' & NamespaceId; readonly model: 'Order' };
    readonly OrderDetail: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'OrderDetail';
    };
    readonly Product: { readonly namespace: 'public' & NamespaceId; readonly model: 'Product' };
    readonly Role: { readonly namespace: 'public' & NamespaceId; readonly model: 'Role' };
    readonly Shipment: { readonly namespace: 'public' & NamespaceId; readonly model: 'Shipment' };
    readonly User: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Membership: {
            readonly fields: {
              readonly mid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly mname: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly score: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly users: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['mid'];
                  readonly targetFields: readonly ['mid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Membership';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly mid: { readonly column: 'mid' };
                readonly mname: { readonly column: 'mname' };
                readonly score: { readonly column: 'score' };
              };
            };
          };
          readonly Order: {
            readonly fields: {
              readonly createat: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
              readonly oid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly uid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly orderDetails: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'OrderDetail';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['oid'];
                  readonly targetFields: readonly ['oid'];
                };
              };
              readonly shipments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Shipment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['oid'];
                  readonly targetFields: readonly ['oid'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['uid'];
                  readonly targetFields: readonly ['uid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Order';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createat: { readonly column: 'createat' };
                readonly oid: { readonly column: 'oid' };
                readonly uid: { readonly column: 'uid' };
              };
            };
          };
          readonly OrderDetail: {
            readonly fields: {
              readonly oid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly pid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly qty: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly unit_price: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 10; readonly scale: 2 };
                };
              };
            };
            readonly relations: {
              readonly order: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['oid'];
                  readonly targetFields: readonly ['oid'];
                };
              };
              readonly product: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['pid'];
                  readonly targetFields: readonly ['pid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'OrderDetail';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly oid: { readonly column: 'oid' };
                readonly pid: { readonly column: 'pid' };
                readonly qty: { readonly column: 'qty' };
                readonly unit_price: { readonly column: 'unit_price' };
              };
            };
          };
          readonly Product: {
            readonly fields: {
              readonly pid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly pname: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 10; readonly scale: 2 };
                };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly orderDetails: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'OrderDetail';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['pid'];
                  readonly targetFields: readonly ['pid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Product';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly pid: { readonly column: 'pid' };
                readonly pname: { readonly column: 'pname' };
                readonly price: { readonly column: 'price' };
                readonly quantity: { readonly column: 'quantity' };
              };
            };
          };
          readonly Role: {
            readonly fields: {
              readonly roleid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly rolename: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
            };
            readonly relations: {
              readonly users: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['roleid'];
                  readonly targetFields: readonly ['roleid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Role';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly roleid: { readonly column: 'roleid' };
                readonly rolename: { readonly column: 'rolename' };
              };
            };
          };
          readonly Shipment: {
            readonly fields: {
              readonly oid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly shipid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
            };
            readonly relations: {
              readonly order: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['oid'];
                  readonly targetFields: readonly ['oid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Shipment';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly oid: { readonly column: 'oid' };
                readonly shipid: { readonly column: 'shipid' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly fullname: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly mid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly roleid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly uid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
            };
            readonly relations: {
              readonly membership: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Membership';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['mid'];
                  readonly targetFields: readonly ['mid'];
                };
              };
              readonly orders: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['uid'];
                  readonly targetFields: readonly ['uid'];
                };
              };
              readonly role: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Role' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['roleid'];
                  readonly targetFields: readonly ['roleid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'User';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly fullname: { readonly column: 'fullname' };
                readonly mid: { readonly column: 'mid' };
                readonly password: { readonly column: 'password' };
                readonly roleid: { readonly column: 'roleid' };
                readonly uid: { readonly column: 'uid' };
                readonly username: { readonly column: 'username' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
